In [1]:
s = "Hi there Sam!"

In [2]:
s.split(" ")


['Hi', 'there', 'Sam!']

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of Earth is {} kilometers.".format(diameter))

The diameter of Earth is 12742 kilometers.


In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
result=d['k1'][3]['tricky'][3]['target'][3]
print(result)

hello


In [7]:
import numpy as np

In [8]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr1=np.ones(10)*5
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
arr2=np.arange(20,35,2)
print(arr2)

[20 22 24 26 28 30 32 34]


In [11]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4, 5, 6])

In [13]:
import pandas as pd
import numpy as np


In [14]:
array=np.random.randint(10,size=(3,2))
array=([9,2,2],
      [3,5,1],
        [4,9,8],
      [3,4,5])
df=pd.DataFrame(array)
df

0  1  2
0  9  2  2
1  3  5  1
2  4  9  8
3  3  4  5

In [15]:
dRan3 = pd.date_range(start ='2023-01-01', end ='2023-02-10').to_pydatetime().tolist()
print(dRan3)

[datetime.datetime(2023, 1, 1, 0, 0), datetime.datetime(2023, 1, 2, 0, 0), datetime.datetime(2023, 1, 3, 0, 0), datetime.datetime(2023, 1, 4, 0, 0), datetime.datetime(2023, 1, 5, 0, 0), datetime.datetime(2023, 1, 6, 0, 0), datetime.datetime(2023, 1, 7, 0, 0), datetime.datetime(2023, 1, 8, 0, 0), datetime.datetime(2023, 1, 9, 0, 0), datetime.datetime(2023, 1, 10, 0, 0), datetime.datetime(2023, 1, 11, 0, 0), datetime.datetime(2023, 1, 12, 0, 0), datetime.datetime(2023, 1, 13, 0, 0), datetime.datetime(2023, 1, 14, 0, 0), datetime.datetime(2023, 1, 15, 0, 0), datetime.datetime(2023, 1, 16, 0, 0), datetime.datetime(2023, 1, 17, 0, 0), datetime.datetime(2023, 1, 18, 0, 0), datetime.datetime(2023, 1, 19, 0, 0), datetime.datetime(2023, 1, 20, 0, 0), datetime.datetime(2023, 1, 21, 0, 0), datetime.datetime(2023, 1, 22, 0, 0), datetime.datetime(2023, 1, 23, 0, 0), datetime.datetime(2023, 1, 24, 0, 0), datetime.datetime(2023, 1, 25, 0, 0), datetime.datetime(2023, 1, 26, 0, 0), datetime.datetime(20

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
df = pd.DataFrame(lists, columns =['ID', 'number','no']) 
print(df)

   ID number  no
0   1    aaa  22
1   2    bbb  25
2   3    ccc  24
